# Generated by Django 4.2.3 on 2023-08-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0002_advert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.ImageField(default='', upload_to='adv/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
